# -*- coding: utf-8 -*-
"""Weather_Api_App.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p01WKb4OFW_fy9Pat0Ey93yJ6GxeDk0m
"""

# Weather Application API Project  

#Required Modules
import requests
from datetime import datetime

# API Key
api_key = '63fcf6ac9a00124665e8461cfe2370bb'
location = input("Enter the City Name : ")

# Link for Generating Weather
complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q=" + location + "&appid=" + api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#Saving the Details in Variables
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

#Time for Printing the Weather
print ("-------------------------------------------------------------")
print ("Weather Status for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current Temperature is: {:.2f} deg C".format(temp_city))
print ("Current Weather Description  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')

# Saving the Values in Text File
with open('weather_info_details.txt','a') as f:
  f.write("\n----------------------------------------\nLocation :")
  f.write(location.title())
  f.write("\nDate | Time :")
  f.write(date_time)
  f.write("\nTemperature :")
  temp = round(temp_city,2)
  f.write(str(temp))
  f.write(" deg C\nWeather Description :")
  f.write(weather_desc.title())
  f.write("\nHumidity :")
  f.write(str(hmdt))
  f.write(" %\n----------------------------------------")
f.close()